### ISSUE TITLE
`scale` parameter not working correctly when using `download` function

### ISSUE THREAD

**Issue by iamtekson** [leftfield-geospatial/geedim#20]
Hi, First of all, thank you very much for this wonderful repo. I am happy that, I am able to download the GEE image from my area of interest. 

When I trying to download the sentinel2 imagery using below code, it downloads the image but the image doesn't have correct `scale`. 

```python
dataset = ee.ImageCollection('COPERNICUS/S2').filterDate('2021-11-01', '2021-11-30').filterBounds(ee_fc).filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE',5)).map(maskS2clouds)
dataset = dataset.median().select(['B4', 'B3', 'B2', 'B8', 'B11', 'B12']).clip(ee_fc)

img = geedim.download.BaseImage(dataset)
img.download(scale = 10, filename="aoi_s2.tif", dtype='float32', region=ee_fc.gemetry(), crs='EPSG:43426')
```

From this code, I got the image having following pixel size, which is kind of strange for me.

```
Dimensions	X: 441 Y: 188 Bands: 6
Origin	80.4700950046142083,29.1321850009392591
Pixel Size	8.983152841195391012e-05,-8.983152841195391012e-05
```

Am I doing anything wrong here?

**Comment by iamtekson** [comment]
Also the another minor error was, when I assign dtype as `float32`, for some images, it download the dtype as `float64`. I don't know how it internally assigning the different dtype then the mentioned one.

**Comment by dugalh** [comment]
Hello.  Good to hear that ``geedim`` is of use to you.

``scale`` is passed to Earth Engine in meters, but it looks like you are downloading in a geographic CRS, so the "Pixel Size" you are seeing is in degrees (8.98e-05 degrees = 10 m at the equator).  To control the scale in meters, you could download in projected CRS like UTM.

**Comment by dugalh** [comment]
FYI, you can do cloud masking and compositing with ``geedim`` e.g.

```python
import geedim as gd
gd.Initialize()

region = {
    "type": "Polygon",
    "coordinates": [[[24, -33.6], [24, -33.53], [23.93, -33.53], [23.93, -33.6], [24, -33.6]]]
}

coll = gd.MaskedCollection.from_name('COPERNICUS/S2')
coll = coll.search('2021-11-01', '2021-11-30', region, cloudless_portion=50)
print(coll.schema_table)
print(coll.properties_table)

comp = coll.composite(method=gd.CompositeMethod.median)
comp.download(
    'aoi_s2.tif', region=region, crs='EPSG:32734', scale=10, dtype='float32',
    bands=['B4', 'B3', 'B2', 'B8', 'B11', 'B12'], overwrite=True
)
```

**Comment by dugalh** [comment]
With the ``dtype`` problem, my tests are passing...  If you have a command line or code snippet that reproduces the behaviour, please provide that in a separate issue.
