### ISSUE TITLE
BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by mht2953658596** [leftfield-geospatial/geedim#22]
I used a library called geemap. One of the functions in this library, `geemap.download_ee_image`, uses the geedim library to download image results calculated through the Earth Engine API.

However, when I use this function to download the image, I can see the progress bar increasing, but when it reaches a certain download progress, it throws an error.

BadZipFile Traceback (most recent call last)
Cell In[23], line 37
34 temp_image.select(["SR_B1", "SR_B2", "SR_B3", "SR_B4","SR_B5", "SR_B7"])
36 y1=1990+i
---> 37 geemap.download_ee_image(temp_image, filename=f'landsat_image_{y1}.tif', scale=30, region=boundary.geometry(),crs='EPSG:4326')
40 for i in range(0,11):
41 start_time=ee.Date('2013-06-01').advance(i,'year')

File d:\anaconda3\envs\myenv\lib\site-packages\geemap\common.py:12925, in download_ee_image(image, filename, region, crs, crs_transform, scale, resampling, dtype, overwrite, num_threads, max_tile_size, max_tile_dim, shape, scale_offset, unmask_value, **kwargs)
12922 kwargs["scale_offset"] = scale_offset
12924 img = gd.download.BaseImage(image)

12925 img.download(filename, overwrite=overwrite, num_threads=num_threads, **kwargs)

File d:\anaconda3\envs\myenv\lib\site-packages\geedim\download.py:955, in BaseImage.download(self, filename, overwrite, num_threads, max_tile_size, max_tile_dim, **kwargs)
953 logger.info(f'Exception: {str(ex)}\nCancelling...')
954 executor.shutdown(wait=False)
--> 955 raise ex
957 bar.update(bar.total - bar.n) # ensure the bar reaches 100%
958 # populate GeoTIFF metadata

File d:\anaconda3\envs\myenv\lib\site-packages\geedim\download.py:951, in BaseImage.download(self, filename, overwrite, num_threads, max_tile_size, max_tile_dim, **kwargs)
949 try:
950 for future in as_completed(futures):
--> 951 future.result()
952 except Exception as ex:
953 logger.info(f'Exception: {str(ex)}\nCancelling...')

File d:\anaconda3\envs\myenv\lib\concurrent\futures_base.py:437, in Future.result(self, timeout)
435 raise CancelledError()
436 elif self._state == FINISHED:
--> 437 return self.__get_result()
439 self._condition.wait(timeout)
441 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File d:\anaconda3\envs\myenv\lib\concurrent\futures_base.py:389, in Future.__get_result(self)
387 if self._exception:
388 try:
--> 389 raise self._exception
390 finally:
391 # Break a reference cycle with the exception in self._exception
392 self = None

File d:\anaconda3\envs\myenv\lib\concurrent\futures\thread.py:57, in _WorkItem.run(self)
54 return
56 try:
---> 57 result = self.fn(*self.args, **self.kwargs)
58 except BaseException as exc:
59 self.future.set_exception(exc)

File d:\anaconda3\envs\myenv\lib\site-packages\geedim\download.py:941, in BaseImage.download.<locals>.download_tile(tile)
939 def download_tile(tile):
940 """Download a tile and write into the destination GeoTIFF. """
--> 941 tile_array = tile.download(session=session, bar=bar)
942 with out_lock:
943 out_ds.write(tile_array, window=tile.window)

File d:\anaconda3\envs\myenv\lib\site-packages\geedim\tile.py:121, in Tile.download(self, session, response, bar)
118 zip_buffer.flush()
120 # extract geotiff from zipped buffer into another buffer
--> 121 zip_file = zipfile.ZipFile(zip_buffer)
122 ext_buffer = BytesIO(zip_file.read(zip_file.filelist[0]))
124 # read the geotiff with a rasterio memory file

File d:\anaconda3\envs\myenv\lib\zipfile.py:1269, in ZipFile.init(self, file, mode, compression, allowZip64, compresslevel, strict_timestamps)
1267 try:
1268 if mode == 'r':
-> 1269 self._RealGetContents()
1270 elif mode in ('w', 'x'):
1271 # set the modified flag so central directory gets written
1272 # even if no files are added to the archive
1273 self._didModify = True

File d:\anaconda3\envs\myenv\lib\zipfile.py:1336, in ZipFile._RealGetContents(self)
1334 raise BadZipFile("File is not a zip file")
1335 if not endrec:
-> 1336 raise BadZipFile("File is not a zip file")
1337 if self.debug > 1:
1338 print(endrec)

BadZipFile: File is not a zip file

How can I solve this problem? Is there a better way to directly download Earth Engine image objects?

**Comment by mht2953658596** [comment]
I briefly reviewed the source code and found that the image download uses a thread pool. However, if one thread encounters an issue, it terminates all download tasks. I think this approach is inefficient in terms of time and data transfer. Is there a way to optimize it? Perhaps adding a retry mechanism to threads that encounter issues could help.

**Comment by dugalh** [comment]
Hello.  The thread pool uses a requests session that is configured for retries.  It is intended to make the download time efficient.

I haven't seen this before.  Can you provide a short code snippet that reproduces the issue please?

**Comment by brownag** [comment]
I have seen this error before, but have not been able to come up with a consistently reproducible example myself. Often re-trying the download of same extent works as expected.

Could possibly add additional error handling to [tile.py L121](https://github.com/leftfield-geospatial/geedim/blob/fa46cb453a69eac74e7145f44c2e4bf09d688359/geedim/tile.py#L121) in the event that the ZIP file is not correctly downloaded/formatted to re-try the tile?

**Comment by dugalh** [comment]
Thanks for the info @brownag.  Theoretically, Requests should be doing retries.  I'm not sure why it doesn't raise an error in this situtation.  I need a way of replicating and testing this before implementing anything.

**Comment by mht2953658596** [comment]
```python
ee.Initialize()



def rm_cloud(image):
    cloud_shadow_bit_mask = (1 << 3)
    clouds_bit_mask = (1 << 5)
    qa = image.select("QA_PIXEL")
    mask = qa.bitwiseAnd(cloud_shadow_bit_mask).eq(0).And(qa.bitwiseAnd(clouds_bit_mask).eq(0))
    return image.updateMask(mask)


def apply_scale_factors5(image):
    optical_bands = image.select('SR_B.').multiply(0.0000275).add(-0.2)
    thermal_bands = image.select('ST_B6').multiply(0.00341802).add(149.0)
    image = image.addBands(optical_bands, None, True)
    image = image.addBands(thermal_bands, None, True)
    return image



def apply_scale_factors8(image):
    optical_bands = image.select('SR_B.').multiply(0.0000275).add(-0.2)
    thermal_bands = image.select('ST_B.*').multiply(0.00341802).add(149.0)
    image = image.addBands(optical_bands, None, True)
    image = image.addBands(thermal_bands, None, True)
    return image



shp_path = r"D:\code_space\gee_test\yyh.shp"
boundary = ee.FeatureCollection(shapefile.Reader(shp_path).__geo_interface__)


if __name__ == '__main__':
    start_time = ee.Date('1990-06-01').advance(1,'year')
    temp_image= ee.ImageCollection('LANDSAT/LT05/C02/T1_L2').filterBounds(boundary.geometry()).filterDate(ee.Date(start_time),ee.Date(start_time).advance((3),'month').advance((29),'day')).map(rm_cloud).map(apply_scale_factors5).median().clip(boundary)
    temp_image.select(["SR_B1", "SR_B2", "SR_B3", "SR_B4","SR_B5", "SR_B7"])  
    y1=1990+1
    geemap.download_ee_image(temp_image, filename=f'./landsat_image_{y1}.tif',  scale=30, region=boundary.geometry(), crs='EPSG:4326')
```



<img width="1223" alt="3bb767ea89f8579d37de753dc4b7700" src="https://github.com/leftfield-geospatial/geedim/assets/59814105/6cad99df-b806-4593-8d19-6f92d9bdf865">




"I don't know if it's because the file I downloaded is too large, or for some other reason?"

**Comment by mht2953658596** [comment]
```
BadZipFile                                Traceback (most recent call last)
Cell In[1], [line 49](vscode-notebook-cell:?execution_count=1&line=49)
     [47](vscode-notebook-cell:?execution_count=1&line=47) temp_image.select(["SR_B1", "SR_B2", "SR_B3", "SR_B4","SR_B5", "SR_B7"])  
     [48](vscode-notebook-cell:?execution_count=1&line=48) y1=1990+1
---> [49](vscode-notebook-cell:?execution_count=1&line=49) geemap.download_ee_image(temp_image, filename=f'./landsat_image_{y1}.tif',  scale=30, region=boundary.geometry(), crs='EPSG:4326')

File d:\anaconda3\envs\myenv\lib\site-packages\geemap\common.py:12925, in download_ee_image(image, filename, region, crs, crs_transform, scale, resampling, dtype, overwrite, num_threads, max_tile_size, max_tile_dim, shape, scale_offset, unmask_value, **kwargs)
  [12922](file:///D:/anaconda3/envs/myenv/lib/site-packages/geemap/common.py:12922)     kwargs["scale_offset"] = scale_offset
  [12924](file:///D:/anaconda3/envs/myenv/lib/site-packages/geemap/common.py:12924) img = gd.download.BaseImage(image)
> [12925](file:///D:/anaconda3/envs/myenv/lib/site-packages/geemap/common.py:12925) img.download(filename, overwrite=overwrite, num_threads=num_threads, **kwargs)

File d:\anaconda3\envs\myenv\lib\site-packages\geedim\download.py:955, in BaseImage.download(self, filename, overwrite, num_threads, max_tile_size, max_tile_dim, **kwargs)
    [953](file:///D:/anaconda3/envs/myenv/lib/site-packages/geedim/download.py:953)         logger.info(f'Exception: {str(ex)}\nCancelling...')
    [954](file:///D:/anaconda3/envs/myenv/lib/site-packages/geedim/download.py:954)         executor.shutdown(wait=False)
--> [955](file:///D:/anaconda3/envs/myenv/lib/site-packages/geedim/download.py:955)         raise ex
    [957](file:///D:/anaconda3/envs/myenv/lib/site-packages/geedim/download.py:957) bar.update(bar.total - bar.n)   # ensure the bar reaches 100%
    [958](file:///D:/anaconda3/envs/myenv/lib/site-packages/geedim/download.py:958) # populate GeoTIFF metadata

File d:\anaconda3\envs\myenv\lib\site-packages\geedim\download.py:951, in BaseImage.download(self, filename, overwrite, num_threads, max_tile_size, max_tile_dim, **kwargs)
    [949](file:///D:/anaconda3/envs/myenv/lib/site-packages/geedim/download.py:949) try:
    [950](file:///D:/anaconda3/envs/myenv/lib/site-packages/geedim/download.py:950)     for future in as_completed(futures):
--> [951](file:///D:/anaconda3/envs/myenv/lib/site-packages/geedim/download.py:951)         future.result()
    [952](file:///D:/anaconda3/envs/myenv/lib/site-packages/geedim/download.py:952) except Exception as ex:
    [953](file:///D:/anaconda3/envs/myenv/lib/site-packages/geedim/download.py:953)     logger.info(f'Exception: {str(ex)}\nCancelling...')

File d:\anaconda3\envs\myenv\lib\concurrent\futures\_base.py:437, in Future.result(self, timeout)
    [435](file:///D:/anaconda3/envs/myenv/lib/concurrent/futures/_base.py:435)     raise CancelledError()
    [436](file:///D:/anaconda3/envs/myenv/lib/concurrent/futures/_base.py:436) elif self._state == FINISHED:
--> [437](file:///D:/anaconda3/envs/myenv/lib/concurrent/futures/_base.py:437)     return self.__get_result()
    [439](file:///D:/anaconda3/envs/myenv/lib/concurrent/futures/_base.py:439) self._condition.wait(timeout)
    [441](file:///D:/anaconda3/envs/myenv/lib/concurrent/futures/_base.py:441) if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File d:\anaconda3\envs\myenv\lib\concurrent\futures\_base.py:389, in Future.__get_result(self)
    [387](file:///D:/anaconda3/envs/myenv/lib/concurrent/futures/_base.py:387) if self._exception:
    [388](file:///D:/anaconda3/envs/myenv/lib/concurrent/futures/_base.py:388)     try:
--> [389](file:///D:/anaconda3/envs/myenv/lib/concurrent/futures/_base.py:389)         raise self._exception
    [390](file:///D:/anaconda3/envs/myenv/lib/concurrent/futures/_base.py:390)     finally:
    [391](file:///D:/anaconda3/envs/myenv/lib/concurrent/futures/_base.py:391)         # Break a reference cycle with the exception in self._exception
    [392](file:///D:/anaconda3/envs/myenv/lib/concurrent/futures/_base.py:392)         self = None

File d:\anaconda3\envs\myenv\lib\concurrent\futures\thread.py:57, in _WorkItem.run(self)
     [54](file:///D:/anaconda3/envs/myenv/lib/concurrent/futures/thread.py:54)     return
     [56](file:///D:/anaconda3/envs/myenv/lib/concurrent/futures/thread.py:56) try:
---> [57](file:///D:/anaconda3/envs/myenv/lib/concurrent/futures/thread.py:57)     result = self.fn(*self.args, **self.kwargs)
     [58](file:///D:/anaconda3/envs/myenv/lib/concurrent/futures/thread.py:58) except BaseException as exc:
     [59](file:///D:/anaconda3/envs/myenv/lib/concurrent/futures/thread.py:59)     self.future.set_exception(exc)

File d:\anaconda3\envs\myenv\lib\site-packages\geedim\download.py:941, in BaseImage.download.<locals>.download_tile(tile)
    [939](file:///D:/anaconda3/envs/myenv/lib/site-packages/geedim/download.py:939) def download_tile(tile):
    [940](file:///D:/anaconda3/envs/myenv/lib/site-packages/geedim/download.py:940)     """Download a tile and write into the destination GeoTIFF. """
--> [941](file:///D:/anaconda3/envs/myenv/lib/site-packages/geedim/download.py:941)     tile_array = tile.download(session=session, bar=bar)
    [942](file:///D:/anaconda3/envs/myenv/lib/site-packages/geedim/download.py:942)     with out_lock:
    [943](file:///D:/anaconda3/envs/myenv/lib/site-packages/geedim/download.py:943)         out_ds.write(tile_array, window=tile.window)

File d:\anaconda3\envs\myenv\lib\site-packages\geedim\tile.py:121, in Tile.download(self, session, response, bar)
    [118](file:///D:/anaconda3/envs/myenv/lib/site-packages/geedim/tile.py:118) zip_buffer.flush()
    [120](file:///D:/anaconda3/envs/myenv/lib/site-packages/geedim/tile.py:120) # extract geotiff from zipped buffer into another buffer
--> [121](file:///D:/anaconda3/envs/myenv/lib/site-packages/geedim/tile.py:121) zip_file = zipfile.ZipFile(zip_buffer)
    [122](file:///D:/anaconda3/envs/myenv/lib/site-packages/geedim/tile.py:122) ext_buffer = BytesIO(zip_file.read(zip_file.filelist[0]))
    [124](file:///D:/anaconda3/envs/myenv/lib/site-packages/geedim/tile.py:124) # read the geotiff with a rasterio memory file

File d:\anaconda3\envs\myenv\lib\zipfile.py:1269, in ZipFile.__init__(self, file, mode, compression, allowZip64, compresslevel, strict_timestamps)
   [1267](file:///D:/anaconda3/envs/myenv/lib/zipfile.py:1267) try:
   [1268](file:///D:/anaconda3/envs/myenv/lib/zipfile.py:1268)     if mode == 'r':
-> [1269](file:///D:/anaconda3/envs/myenv/lib/zipfile.py:1269)         self._RealGetContents()
   [1270](file:///D:/anaconda3/envs/myenv/lib/zipfile.py:1270)     elif mode in ('w', 'x'):
   [1271](file:///D:/anaconda3/envs/myenv/lib/zipfile.py:1271)         # set the modified flag so central directory gets written
   [1272](file:///D:/anaconda3/envs/myenv/lib/zipfile.py:1272)         # even if no files are added to the archive
   [1273](file:///D:/anaconda3/envs/myenv/lib/zipfile.py:1273)         self._didModify = True

File d:\anaconda3\envs\myenv\lib\zipfile.py:1336, in ZipFile._RealGetContents(self)
   [1334](file:///D:/anaconda3/envs/myenv/lib/zipfile.py:1334)     raise BadZipFile("File is not a zip file")
   [1335](file:///D:/anaconda3/envs/myenv/lib/zipfile.py:1335) if not endrec:
-> [1336](file:///D:/anaconda3/envs/myenv/lib/zipfile.py:1336)     raise BadZipFile("File is not a zip file")
   [1337](file:///D:/anaconda3/envs/myenv/lib/zipfile.py:1337) if self.debug > 1:
   [1338](file:///D:/anaconda3/envs/myenv/lib/zipfile.py:1338)     print(endrec)

BadZipFile: File is not a zip file
```

**Comment by brownag** [comment]
> Thanks for the info @brownag. Theoretically, Requests should be doing retries. I'm not sure why it doesn't raise an error in this situtation. I need a way of replicating and testing this before implementing anything.

Well, I think an unhandled error (i.e. `BadZipFile("File is not a zip file")`) is raised by `zipfile`. The download appears to complete successfully, but the payload is not a valid ZIP file, causing subsequent unpacking of the result to fail. I imagine some sort of atypical response is occurring but not detected. It may be network specific--I have encountered it probably most often when on my work network

Understood that you need a reprex. Will try to find a case where this can happen fairly consistently. Like @mht2953658596 says I have seen this with fairly large downloads--where just one tile throwing this error stops the whole process. I imagine it is not specific to the total download size but rather just that the number of tiles involved makes it more likely that one will fail.

**Comment by mht2953658596** [comment]
![Uploading 1abf7b198ebfcd37fd85f98d76bb81d.png…]()

**Comment by mht2953658596** [comment]
![1abf7b198ebfcd37fd85f98d76bb81d](https://github.com/leftfield-geospatial/geedim/assets/59814105/a6576b6f-7f70-4afc-8b13-a63b779fe23a)

**Comment by dugalh** [comment]
> ![1abf7b198ebfcd37fd85f98d76bb81d](https://private-user-images.githubusercontent.com/59814105/340985508-a6576b6f-7f70-4afc-8b13-a63b779fe23a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODY2MTYsIm5iZiI6MTcxODc4NjMxNiwicGF0aCI6Ii81OTgxNDEwNS8zNDA5ODU1MDgtYTY1NzZiNmYtN2Y3MC00YWZjLThiMTMtYTYzYjc3OWZlMjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA4MzgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ZDViODYwYWRhOGVmMWZkZDZhNmY4MDU1OTFjYTYzNTZlY2NmMzg0ZWNlYmY2ZmY3ZTQ5NThiNGI5OGRhOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uNpoaiW6wWHrv0MCN1-JpbneJWSusxDx4LAckp02eWg)

This is more what I was expecting where Requests raises an error.  It does appear to be a network specific reliability issue.  I am going to work on a retry for the tile download that will hopefully fix or at least reduce these problems.

**Comment by mht2953658596** [comment]
@dugalh  Thank you for your effort. I hope you can add a feature to retry the download of individual tiles in case of timeout or failure. This way, a single tile download failure or blockage won't prevent the entire image from being downloaded.

**Comment by dugalh** [comment]
> ![1abf7b198ebfcd37fd85f98d76bb81d](https://private-user-images.githubusercontent.com/59814105/340985508-a6576b6f-7f70-4afc-8b13-a63b779fe23a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4OTAzNDgsIm5iZiI6MTcxODg5MDA0OCwicGF0aCI6Ii81OTgxNDEwNS8zNDA5ODU1MDgtYTY1NzZiNmYtN2Y3MC00YWZjLThiMTMtYTYzYjc3OWZlMjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDEzMjcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNzQ2OTc3OTM3NzhkYjRhOWExY2QyZmY3MmI5OGNkODk4ZDNmN2IwNmQxZGEwOGM5Yjc3MzUxMmVmMjQ2YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8x3Xh7qod-DebIzFv78Jpj34aPhGrAAF3Rjmf4ipsJk)

I think this is the reason Requests doesn't retry in this case: psf/requests#6512
